package control

import (
	"database/sql"
	"encoding/hex"
	"errors"
	"net/http"
	"strings"
	"time"
)

// A connection is a durable authorization lineage, not a forwarding lease.
// Its transport sessions may expire or be replaced without reviving a revoked
// lineage. Tokens stay hashed; retry credentials are generated by the caller.
type connectionRecord struct {
	ID, Tenant, Broker, Relay, AccountHash, DeviceHash string
	Session, Request, TokenHash, Revoked               string
	Version                                            int
	Generation, PriorGeneration                        uint64
}

type connectionRequest struct {
	Broker             string  `json:"broker_id"`
	Relay              string  `json:"relay_mode"`
	ExpectedGeneration *uint64 `json:"expected_generation"`
	Request            string  `json:"request_id"`
	Token              string  `json:"session_token"`
}

func validConnectionID(id string) bool {
	if len(id) != 36 {
		return false
	}
	for i, c := range []byte(id) {
		if i == 8 || i == 13 || i == 18 || i == 23 {
			if c != '-' {
				return false
			}
		} else if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}
func validConnectionToken(token string) bool {
	if len(token) != 64 || strings.ToLower(token) != token {
		return false
	}
	_, err := hex.DecodeString(token)
	return err == nil
}
func connectionFailure(status int, code, message string, generation uint64) error {
	return &apiError{code: status, message: message, reason: code, generation: generation}
}
func readConnection(q interface{ QueryRow(string, ...any) *sql.Row }, id string) (connectionRecord, error) {
	var c connectionRecord
	err := q.QueryRow("SELECT id,tenant_id,broker_id,relay_mode,account_hash,device_hash,tenant_version,generation,current_session_id,request_id,prior_generation,session_token_hash,revoked_reason FROM connections WHERE id=?", id).Scan(&c.ID, &c.Tenant, &c.Broker, &c.Relay, &c.AccountHash, &c.DeviceHash, &c.Version, &c.Generation, &c.Session, &c.Request, &c.PriorGeneration, &c.TokenHash, &c.Revoked)
	return c, err
}
func connectionCredential(q interface{ QueryRow(string, ...any) *sql.Row }, hash, kind, tenant, broker string, version int) (bool, error) {
	var count int
	err := q.QueryRow("SELECT COUNT(*) FROM tokens WHERE hash=? AND kind=? AND tenant_id=? AND version=? AND expires_at>? AND COALESCE(broker_id,'')=?", hash, kind, tenant, version, now(), broker).Scan(&count)
	return count == 1, err
}

type observedSessionRevocation struct {
	cause      error
	connection connectionRecord
}

func (e *observedSessionRevocation) Error() string { return e.cause.Error() }
func (e *observedSessionRevocation) Unwrap() error { return e.cause }

// Call after a handler has unwound its failed transaction. Mark only the
// exact transport that supplied the evidence; expiry/GC must never erase an
// already observed live-session credential revocation.
func (s *Server) persistObservedRevocation(err error) error {
	var observed *observedSessionRevocation
	if !errors.As(err, &observed) {
		return err
	}
	c := observed.connection
	result, e := s.db.Exec("UPDATE connections SET revoked_reason='session_credential_revoked',updated_at=? WHERE id=? AND generation=? AND current_session_id=? AND session_token_hash=? AND revoked_reason=''", now(), c.ID, c.Generation, c.Session, c.TokenHash)
	if e != nil {
		return e
	}
	changed, e := result.RowsAffected()
	if e != nil {
		return e
	}
	if changed != 0 {
		s.revokeSession(c.Session)
		s.notifyWSBroker(c.Broker)
	}
	return err
}

func checkConnection(q interface{ QueryRow(string, ...any) *sql.Row }, c connectionRecord) error {
	if c.Revoked != "" {
		return connectionFailure(403, "connection_revoked", "connection was explicitly revoked", c.Generation)
	}
	var version int
	var status string
	err := q.QueryRow("SELECT version,status FROM tenants WHERE id=?", c.Tenant).Scan(&version, &status)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return err
	}
	if errors.Is(err, sql.ErrNoRows) || version != c.Version || status != "active" {
		return connectionFailure(403, "credential_revoked", "connection identity is no longer authorized", c.Generation)
	}
	account, err := connectionCredential(q, c.AccountHash, "account", c.Tenant, "", c.Version)
	if err != nil {
		return err
	}
	device, err := connectionCredential(q, c.DeviceHash, "device", c.Tenant, c.Broker, c.Version)
	if err != nil {
		return err
	}
	if !account || !device {
		return connectionFailure(403, "credential_revoked", "connection credential was expired or revoked", c.Generation)
	}
	// Expiration of both transport rows is recoverable. Removing a still-live
	// transport token is revocation, not permission to mint a replacement.
	at := now()
	var revoked int
	if err = q.QueryRow("SELECT COUNT(*) FROM sessions s WHERE s.id=? AND s.expires_at>? AND NOT EXISTS(SELECT 1 FROM tokens t WHERE t.hash=? AND t.kind='session' AND t.session_id=s.id AND t.version=? AND t.expires_at>?)", c.Session, at, c.TokenHash, c.Version, at).Scan(&revoked); err != nil {
		return err
	}
	if revoked != 0 {
		return &observedSessionRevocation{cause: connectionFailure(403, "credential_revoked", "session credential was revoked", c.Generation), connection: c}
	}
	return nil
}
func (s *Server) managedSession(v Session) error {
	if v.ConnectionID == "" {
		return nil
	}
	c, err := readConnection(s.db, v.ConnectionID)
	if errors.Is(err, sql.ErrNoRows) {
		return connectionFailure(403, "connection_unknown", "connection lineage is unavailable", v.Generation)
	}
	if err != nil {
		return err
	}
	if err = checkConnection(s.db, c); err != nil {
		return s.persistObservedRevocation(err)
	}
	if c.Session != v.ID || c.Generation != v.Generation {
		return connectionFailure(409, "session_replaced", "session was replaced", c.Generation)
	}
	return nil
}
func txManagedSession(tx *sql.Tx, v Session) error {
	if v.ConnectionID == "" {
		return nil
	}
	c, err := readConnection(tx, v.ConnectionID)
	if errors.Is(err, sql.ErrNoRows) {
		return connectionFailure(403, "connection_unknown", "connection lineage is unavailable", v.Generation)
	}
	if err != nil {
		return err
	}
	if err = checkConnection(tx, c); err != nil {
		return err
	}
	if c.Session != v.ID || c.Generation != v.Generation {
		return connectionFailure(409, "session_replaced", "session was replaced", c.Generation)
	}
	return nil
}

// Already authenticated managed WebSockets retain this connection ID even
// after transport GC. Classify lineage authorization before missing-token
// errors can erase the difference between expiry/replacement and revocation.
func (s *Server) connectionSessionState(id, sid string, identity principal) error {
	c, err := readConnection(s.db, id)
	if errors.Is(err, sql.ErrNoRows) {
		return connectionFailure(403, "credential_revoked", "connection authorization is no longer available", 0)
	}
	if err != nil {
		return err
	}
	if c.Tenant != identity.tenant || c.Broker != identity.broker || c.Version != identity.version {
		return connectionFailure(403, "credential_revoked", "connection identity changed", c.Generation)
	}
	if err = checkConnection(s.db, c); err != nil {
		return s.persistObservedRevocation(err)
	}
	if c.Session != sid {
		return connectionFailure(409, "session_replaced", "session was replaced", c.Generation)
	}
	var expiry int64
	err = s.db.QueryRow("SELECT expires_at FROM sessions WHERE id=?", sid).Scan(&expiry)
	if errors.Is(err, sql.ErrNoRows) || err == nil && expiry <= now() {
		return connectionFailure(410, "session_expired", "session lease expired", c.Generation)
	}
	return err
}

func revokeConnections(tx *sql.Tx, where, reason string, args ...any) error {
	values := append([]any{reason, now()}, args...)
	_, err := tx.Exec("UPDATE connections SET revoked_reason=?,updated_at=? WHERE revoked_reason='' AND ("+where+")", values...)
	return err
}
func (s *Server) connectionSession(w http.ResponseWriter, r *http.Request) error {
	p, err := s.auth(r, "account")
	if err != nil {
		return err
	}
	id := r.PathValue("id")
	var body connectionRequest
	if err = decode(w, r, &body); err != nil {
		return err
	}
	if !validConnectionID(id) || !validConnectionID(body.Broker) || !validConnectionID(body.Request) || !validConnectionToken(body.Token) || body.ExpectedGeneration == nil || body.Relay != "auto" && body.Relay != "never" && body.Relay != "force" {
		return fail(400, "invalid connection request")
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err = txPrincipal(tx, r, p); err != nil {
		return err
	}
	c, err := readConnection(tx, id)
	fresh := errors.Is(err, sql.ErrNoRows)
	if err != nil && !fresh {
		return err
	}
	if fresh && *body.ExpectedGeneration != 0 {
		return connectionFailure(404, "connection_unknown", "connection lineage is unavailable", 0)
	}
	if !fresh {
		if c.Tenant != p.tenant || c.Broker != body.Broker || c.Relay != body.Relay || c.AccountHash != tokenHash(bearer(r)) {
			return connectionFailure(403, "connection_revoked", "connection scope or credential changed", c.Generation)
		}
		if err = checkConnection(tx, c); err != nil {
			return err
		}
	}
	var lease int64
	if err = tx.QueryRow("SELECT lease_expires_at FROM brokers WHERE id=? AND tenant_id=?", body.Broker, p.tenant).Scan(&lease); errors.Is(err, sql.ErrNoRows) {
		return connectionFailure(404, "broker_missing", "broker not found", 0)
	} else if err != nil {
		return err
	}
	if lease <= now() {
		return connectionFailure(409, "broker_offline", "broker heartbeat is required", c.Generation)
	}
	if body.Relay == "force" {
		var relay int
		if err = tx.QueryRow("SELECT relay_enabled FROM tenants WHERE id=?", p.tenant).Scan(&relay); err != nil {
			return err
		}
		if relay == 0 || s.turn == nil {
			return connectionFailure(403, "connection_revoked", "forced relay is unavailable", c.Generation)
		}
	}
	if !fresh && body.Request == c.Request {
		if *body.ExpectedGeneration != c.PriorGeneration || tokenHash(body.Token) != c.TokenHash {
			return connectionFailure(409, "connection_conflict", "request replay differs", c.Generation)
		}
		var expiry int64
		if err = tx.QueryRow("SELECT expires_at FROM sessions WHERE id=?", c.Session).Scan(&expiry); errors.Is(err, sql.ErrNoRows) || err == nil && expiry <= now() {
			return connectionFailure(410, "session_expired", "the attempted session expired", c.Generation)
		} else if err != nil {
			return err
		}
		if err = tx.Commit(); err != nil {
			return err
		}
		s.write(w, 200, map[string]any{"session_id": c.Session, "connection_id": id, "generation": c.Generation, "expires_at": fromTimestamp(expiry)})
		return nil
	}
	if !fresh && *body.ExpectedGeneration != c.Generation {
		return connectionFailure(409, "connection_conflict", "connection generation changed", c.Generation)
	}
	if c.Generation >= 2147483647 {
		return connectionFailure(409, "connection_conflict", "connection generation limit reached", c.Generation)
	}
	var count int
	if fresh {
		if err = tx.QueryRow("SELECT COUNT(*) FROM connections WHERE tenant_id=? AND revoked_reason=''", p.tenant).Scan(&count); err != nil {
			return err
		}
		if count >= s.cfg.MaxSessionsPerTenant {
			return fail(429, "tenant connection limit reached")
		}
		// Retained tombstones protect lost initial replies from recreating a
		// revoked ID. They consume the separate global storage bound, not
		// the tenant's active-connection admission quota.
		if err = tx.QueryRow("SELECT COUNT(*) FROM connections").Scan(&count); err != nil {
			return err
		}
		if count >= 10000 {
			return fail(429, "global connection storage limit reached")
		}
		if err = tx.QueryRow("SELECT hash FROM tokens WHERE kind='device' AND tenant_id=? AND broker_id=? AND version=? AND expires_at>? ORDER BY expires_at DESC LIMIT 1", p.tenant, body.Broker, p.version, now()).Scan(&c.DeviceHash); errors.Is(err, sql.ErrNoRows) {
			return connectionFailure(403, "credential_revoked", "broker credential is unavailable", 0)
		} else if err != nil {
			return err
		}
		c.AccountHash = tokenHash(bearer(r))
		c.Version = p.version
	}
	if err = tx.QueryRow("SELECT COUNT(*) FROM sessions WHERE tenant_id=? AND expires_at>? AND id<>?", p.tenant, now(), c.Session).Scan(&count); err != nil {
		return err
	}
	if count >= s.cfg.MaxSessionsPerTenant {
		return fail(429, "tenant session limit reached")
	}
	if err = tx.QueryRow("SELECT COUNT(*) FROM sessions WHERE expires_at>? AND id<>?", now(), c.Session).Scan(&count); err != nil {
		return err
	}
	if count >= 10000 {
		return fail(429, "global session limit reached")
	}
	// A caller must not reuse one transport credential for two generations.
	if err = tx.QueryRow("SELECT COUNT(*) FROM connection_sessions WHERE token_hash=?", tokenHash(body.Token)).Scan(&count); err != nil {
		return err
	}
	if count != 0 {
		return connectionFailure(409, "connection_conflict", "session credential was already used", c.Generation)
	}
	if err = tx.QueryRow("SELECT COUNT(*) FROM connection_sessions WHERE connection_id=? AND request_id=?", id, body.Request).Scan(&count); err != nil {
		return err
	}
	if count != 0 {
		return connectionFailure(409, "connection_conflict", "request identifier was already used", c.Generation)
	}
	if err = tx.QueryRow("SELECT COUNT(*) FROM tokens WHERE hash=?", tokenHash(body.Token)).Scan(&count); err != nil {
		return err
	}
	if count != 0 {
		return connectionFailure(409, "connection_conflict", "session credential was already used", c.Generation)
	}
	oldSession := c.Session
	if oldSession != "" {
		if _, err = tx.Exec("DELETE FROM tokens WHERE kind='session' AND session_id=?", oldSession); err != nil {
			return err
		}
		if _, err = tx.Exec("DELETE FROM sessions WHERE id=?", oldSession); err != nil {
			return err
		}
	}
	generation := c.Generation + 1
	sid := uuid()
	expiry := time.Now().Add(s.cfg.SessionTTL)
	if _, err = tx.Exec("INSERT INTO sessions(id,tenant_id,broker_id,relay_mode,expires_at) VALUES(?,?,?,?,?)", sid, p.tenant, body.Broker, body.Relay, timestamp(expiry)); err != nil {
		return err
	}
	if _, err = tx.Exec("INSERT INTO tokens(hash,kind,tenant_id,broker_id,session_id,version,expires_at) VALUES(?,'session',?,?,?,?,?)", tokenHash(body.Token), p.tenant, body.Broker, sid, p.version, timestamp(expiry)); err != nil {
		return err
	}
	if fresh {
		_, err = tx.Exec("INSERT INTO connections(id,tenant_id,broker_id,relay_mode,account_hash,device_hash,tenant_version,generation,current_session_id,request_id,prior_generation,session_token_hash,revoked_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'',?,?)", id, p.tenant, body.Broker, body.Relay, c.AccountHash, c.DeviceHash, c.Version, generation, sid, body.Request, *body.ExpectedGeneration, tokenHash(body.Token), now(), now())
	} else {
		_, err = tx.Exec("UPDATE connections SET generation=?,current_session_id=?,request_id=?,prior_generation=?,session_token_hash=?,updated_at=? WHERE id=?", generation, sid, body.Request, *body.ExpectedGeneration, tokenHash(body.Token), now(), id)
	}
	if err != nil {
		return err
	}
	if _, err = tx.Exec("INSERT INTO connection_sessions(session_id,connection_id,generation,request_id,prior_generation,token_hash,created_at) VALUES(?,?,?,?,?,?,?)", sid, id, generation, body.Request, *body.ExpectedGeneration, tokenHash(body.Token), now()); err != nil {
		return err
	}
	// History is bounded. Forgotten old IDs fail closed and never mint grants.
	if _, err = tx.Exec("DELETE FROM connection_sessions WHERE connection_id=? AND generation<?", id, int64(generation)-256); err != nil {
		return err
	}
	if err = tx.Commit(); err != nil {
		return err
	}
	if oldSession != "" {
		s.revokeSession(oldSession)
	}
	s.notifyWSBroker(body.Broker)
	s.write(w, 201, map[string]any{"session_id": sid, "connection_id": id, "generation": generation, "expires_at": fromTimestamp(timestamp(expiry))})
	return nil
}

// Explicit closure is independent of a transport token that may already have
// expired. Account owners and the bound broker device may revoke the lineage.
func (s *Server) deleteConnection(w http.ResponseWriter, r *http.Request) error {
	p, err := s.auth(r, "account", "device")
	if err != nil {
		return err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err = txPrincipal(tx, r, p); err != nil {
		return err
	}
	c, err := readConnection(tx, r.PathValue("id"))
	if errors.Is(err, sql.ErrNoRows) {
		return connectionFailure(404, "connection_unknown", "connection not found", 0)
	} else if err != nil {
		return err
	}
	if c.Tenant != p.tenant || p.kind == "device" && c.Broker != p.broker {
		return fail(404, "connection not found")
	}
	if err = revokeConnections(tx, "id=?", "closed", c.ID); err != nil {
		return err
	}
	if _, err = tx.Exec("DELETE FROM tokens WHERE kind='session' AND session_id IN (SELECT session_id FROM connection_sessions WHERE connection_id=?)", c.ID); err != nil {
		return err
	}
	if _, err = tx.Exec("DELETE FROM sessions WHERE id IN (SELECT session_id FROM connection_sessions WHERE connection_id=?)", c.ID); err != nil {
		return err
	}
	if err = tx.Commit(); err != nil {
		return err
	}
	s.revokeSession(c.Session)
	s.notifyWSBroker(c.Broker)
	s.write(w, 200, map[string]bool{"deleted": true})
	return nil
}

func (s *Server) deleteSessionLineage(r *http.Request) (bool, error) {
	var id string
	err := s.db.QueryRow("SELECT connection_id FROM connection_sessions WHERE session_id=?", r.PathValue("id")).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return true, err
	}
	p, err := s.auth(r, "account", "device", "session")
	if err != nil {
		return true, err
	}
	tx, err := s.db.Begin()
	if err != nil {
		return true, err
	}
	defer tx.Rollback()
	if err = txPrincipal(tx, r, p); err != nil {
		return true, err
	}
	c, err := readConnection(tx, id)
	if err != nil {
		return true, connectionFailure(404, "connection_unknown", "connection not found", 0)
	}
	if c.Tenant != p.tenant || p.kind == "device" && p.broker != c.Broker || p.kind == "session" && (p.broker != c.Broker || p.session != r.PathValue("id")) {
		return true, fail(403, "session scope denied")
	}
	if err = revokeConnections(tx, "id=?", "session_deleted", c.ID); err != nil {
		return true, err
	}
	if _, err = tx.Exec("DELETE FROM tokens WHERE kind='session' AND session_id IN (SELECT session_id FROM connection_sessions WHERE connection_id=?)", c.ID); err != nil {
		return true, err
	}
	if _, err = tx.Exec("DELETE FROM sessions WHERE id IN (SELECT session_id FROM connection_sessions WHERE connection_id=?)", c.ID); err != nil {
		return true, err
	}
	if err = tx.Commit(); err != nil {
		return true, err
	}
	s.revokeSession(c.Session)
	s.notifyWSBroker(c.Broker)
	return true, nil
}

func (s *Server) connectionDiscovery(w http.ResponseWriter, r *http.Request) error {
	s.write(w, 200, map[string]any{"connection_recovery_version": 1, "connection_recovery_protocol": "connections-v1", "signaling": wsProtocol})
	return nil
}

func (s *Server) pruneConnections() error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	dead := "NOT EXISTS(SELECT 1 FROM tokens WHERE tokens.hash=connections.account_hash AND tokens.kind='account' AND tokens.expires_at>?) OR NOT EXISTS(SELECT 1 FROM tokens WHERE tokens.hash=connections.device_hash AND tokens.kind='device' AND tokens.expires_at>?) OR NOT EXISTS(SELECT 1 FROM tenants WHERE tenants.id=connections.tenant_id AND tenants.version=connections.tenant_version AND tenants.status='active')"
	ids := "SELECT session_id FROM connection_sessions WHERE connection_id IN (SELECT id FROM connections WHERE " + dead + ")"
	if _, err = tx.Exec("DELETE FROM tokens WHERE kind='session' AND session_id IN ("+ids+")", now(), now()); err != nil {
		return err
	}
	if _, err = tx.Exec("DELETE FROM sessions WHERE id IN ("+ids+")", now(), now()); err != nil {
		return err
	}
	result, err := tx.Exec("DELETE FROM connections WHERE "+dead, now(), now())
	if err != nil {
		return err
	}
	if err = tx.Commit(); err != nil {
		return err
	}
	if count, _ := result.RowsAffected(); count != 0 {
		s.ws.wake(func(*wsPeer) bool { return true })
	}
	return nil
}
